version: '3.8'

services:
  bobcofer-bot:
    build: .
    container_name: bobcofer-bot
    restart: unless-stopped
    env_file:
      - .env
    # Пробрасываем порт VNC на локальный хост (5900)
    ports:
      - "5900:5900"  # VNC для браузера
    # Объёмы (volumes) для хранения данных, логов, конфигов и т.д.
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./scheduled.json:/app/scheduled.json
      - ./contacts.json:/app/contacts.json
      - ./conf.json:/app/conf.json
      - ./token.json:/app/token.json
    # Для отображения графики — установите DISPLAY
    environment:
      - DISPLAY=:99
