services:
  bobcofer-bot:
    build: .
    container_name: bobcofer-bot
    network_mode: "host"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISPLAY=:0
      - BROWSER=google-chrome
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      # X11 socket для GUI приложений
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      
      # Альтернативный файл авторизации
      - /tmp/.docker.xauth:/tmp/.docker.xauth:ro
      
      # Данные бота  
      - ./data:/app/data
      - ./logs:/app/logs
      - ./scheduled.json:/app/scheduled.json
      - ./contacts.json:/app/contacts.json
      - ./conf.json:/app/conf.json
      - ./token.json:/app/token.json
