services:
  bobcofer-bot:
    build: .
    container_name: bobcofer-bot
    network_mode: "host"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISPLAY=:0
      - BROWSER=google-chrome
      - XAUTHORITY=/root/.Xauthority
      
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/myuser/.Xauthority:/root/.Xauthority:ro
      - ./data:/app/data
      - ./logs:/app/logs
      - ./scheduled.json:/app/scheduled.json
      - ./contacts.json:/app/contacts.json
      - ./conf.json:/app/conf.json
      - ./token.json:/app/token.json
 wa-automate:
    image: openwa/wa-automate:latest
    container_name: wa-automate
    init: true
    restart: unless-stopped
    volumes:
      - wa-sessions:/sessions
    ports:
      - "8080:8080"
    environment:
      - WA_SESSION_ID=mybot
      - WA_DISABLE_SPINS=true

volumes:
  wa-sessions:
