services:
  wa-automate:
    image: openwa/wa-automate:latest
    container_name: wa-automate
    init: true
    restart: unless-stopped
    volumes:
      - wa-sessions:/sessions
    ports:
      - "8002:8002"  # Исправлен порт на 8002 (из логов wa-automate)
    environment:
      - WA_SESSION_ID=mybot
      - WA_DISABLE_SPINS=true
      - WA_PORT=8002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/getAllChats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  bobcofer-bot:
    build: .
    container_name: bobcofer-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./scheduled.json:/app/scheduled.json
      - ./contacts.json:/app/contacts.json
      - ./conf.json:/app/conf.json
      - ./token.json:/app/token.json
    depends_on:
      wa-automate:
        condition: service_healthy
    environment:
      - WA_AUTOMATE_URL=http://wa-automate:8002  # Используем имя сервиса

volumes:
  wa-sessions:
